import { ThemeConfig, ThemePreset } from '../types';

export const THEME_OPTIONS: ThemeConfig[] = [
  {
    id: 'slate',
    name: 'Modern Slate',
    description: 'Crisp clean neutral canvas with cool slate accents',
    bgHex: '#f8fafc',
    cardHex: '#ffffff',
    textHex: '#0f172a',
    swatchGradient: 'from-slate-100 to-slate-200 border-slate-300',
    isDark: false,
    appClass: 'theme-slate bg-slate-50 text-slate-900',
  },
  {
    id: 'midnight',
    name: 'Midnight Navy',
    description: 'Deep nocturnal blue dark mode for night reporting',
    bgHex: '#0b1329',
    cardHex: '#131f3d',
    textHex: '#f1f5f9',
    swatchGradient: 'from-slate-900 to-indigo-950 border-indigo-500',
    isDark: true,
    appClass: 'theme-midnight bg-[#0b1329] text-slate-100 dark',
  },
  {
    id: 'emerald',
    name: 'Eco Emerald',
    description: 'Fresh municipal mint & parkland green background',
    bgHex: '#f0fdf4',
    cardHex: '#ffffff',
    textHex: '#064e3b',
    swatchGradient: 'from-emerald-100 to-teal-100 border-emerald-400',
    isDark: false,
    appClass: 'theme-emerald bg-emerald-50/70 text-slate-900',
  },
  {
    id: 'sky',
    name: 'Coastal Azure',
    description: 'Vibrant ocean breeze sky blue civic backdrop',
    bgHex: '#f0f9ff',
    cardHex: '#ffffff',
    textHex: '#0c4a6e',
    swatchGradient: 'from-sky-100 to-blue-200 border-sky-400',
    isDark: false,
    appClass: 'theme-sky bg-sky-50 text-slate-900',
  },
  {
    id: 'amber',
    name: 'Warm Sandstone',
    description: 'Comforting warm sunlit sand & golden amber hue',
    bgHex: '#fffbeb',
    cardHex: '#ffffff',
    textHex: '#78350f',
    swatchGradient: 'from-amber-100 to-yellow-100 border-amber-400',
    isDark: false,
    appClass: 'theme-amber bg-amber-50/70 text-slate-900',
  },
  {
    id: 'twilight',
    name: 'Twilight Violet',
    description: 'Sophisticated amethyst & twilight evening hue',
    bgHex: '#faf5ff',
    cardHex: '#ffffff',
    textHex: '#581c87',
    swatchGradient: 'from-purple-100 to-indigo-100 border-purple-400',
    isDark: false,
    appClass: 'theme-twilight bg-purple-50/60 text-slate-900',
  },
  {
    id: 'obsidian',
    name: 'Obsidian OLED',
    description: 'Pure pitch black OLED background for maximum contrast',
    bgHex: '#000000',
    cardHex: '#121212',
    textHex: '#ffffff',
    swatchGradient: 'from-black to-neutral-900 border-neutral-600',
    isDark: true,
    appClass: 'theme-obsidian bg-black text-white dark',
  },
];

export function getThemeConfig(id: ThemePreset): ThemeConfig {
  return THEME_OPTIONS.find((t) => t.id === id) || THEME_OPTIONS[0];
}
